export enum UserRole {
    USER = 'USER',
    ADMIN ='ADMIN'
}
export enum WorkMode {
    REMOTE = 'REMOTE',
    HYBRID = 'HYBRID',
    ON_SITE = 'ON_SITE'
}

export enum ApplicationStatus {
SAVED = 'SAVED',
APPLIED = 'APPLIED',
SCREENING = 'SCREENING',
ASSESSMENT = 'ASSESSMENT',
INTERVIEW = 'INTERVIEW',
FINAL_INTERVIEW = 'FINAL_INTERVIEW',
OFFER = 'OFFER',
HIRED= 'HIRED',
REJECTED = 'REJECTED',
WITHDRAWN = 'WITHDRAWN'
}

export enum InterviewType {
  PHONE_SCREEN = 'PHONE_SCREEN',
  TECHNICAL_SCREEN = 'TECHNICAL_SCREEN',
  TAKE_HOME_ASSESSMENT = 'TAKE_HOME_ASSESSMENT',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  CODING_ALGORITHM = 'CODING_ALGORITHM',
  BEHAVIORAL = 'BEHAVIORAL',
  MANAGERIAL = 'MANAGERIAL',
  CULTURE_FIT = 'CULTURE_FIT',
  HR_FINAL = 'HR_FINAL',
  OFFER_DISCUSSION = 'OFFER_DISCUSSION',
}

export enum InterviewStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  RESUME = 'RESUME',
  COVER_LETTER = 'COVER_LETTER',
  TRANSCRIPT = 'TRANSCRIPT',
  CERTIFICATE = 'CERTIFICATE',
  PORTFOLIO = 'PORTFOLIO',
  OTHER = 'OTHER',
}